### ISSUE TITLE
npm sku storybook removes forward slashes, storybook server does not start

### ISSUE THREAD

**Issue by mauriciomateus** [seek-oss/sku#650] opened 2021-09-29 01:29 UTC
Hi:

After running: 
$ npx sku storybook

The storybook server does not start. The script removes the forwards slashes from the path on Windows. Please see the error below:

`
$ npx sku storybook

--------------------------------------------------------------------------------
  
    @seek/sku-telemetry not installed
  
    To help us improve sku, please install our private telemetry package        
    that gives us insights on usage, errors and performance.

    yarn add --dev @seek/sku-telemetry

    Non SEEK based usage can disable this message with `SKU_TELEMETRY=false`    
  
--------------------------------------------------------------------------------
  
info @storybook/react v6.3.8
info 
info => Loading presets
info => Loading 1 config file in "C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start"
info => Adding stories defined in "C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start\main.js"
info => Using implicit CSS loaders

--------------------------------------------------------------------------------
  
    @seek/sku-telemetry not installed
  
    To help us improve sku, please install our private telemetry package        
    that gives us insights on usage, errors and performance.

    yarn add --dev @seek/sku-telemetry

    Non SEEK based usage can disable this message with `SKU_TELEMETRY=false`    
  
--------------------------------------------------------------------------------

info => Loading custom Webpack config (full-control mode).
<i> [webpack-dev-middleware] wait until bundle finished

info => Ignoring cached manager due to change in manager config
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 4.45 MiB (id hint: vendors)
  assets by status 4.14 MiB [big]
    asset vendors-node_modules_storybook_core-client_dist_esm_globals_polyfills_js-node_modules_storybo-26f588.manager.bundle.js 3.77 MiB [emitted] [big] (id hint: vendors)        
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 196 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 112 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.6 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 13.5 KiB [emitted] (name: runtime~main)
asset index.html 3.11 KiB [emitted]
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.27 KiB [emitted]
asset main.manager.bundle.js 818 bytes [emitted] (name: main)
Entrypoint main [big] 3.79 MiB = runtime~main.manager.bundle.js 13.5 KiB vendors-node_modules_storybook_core-client_dist_esm_globals_polyfills_js-node_modules_storybo-26f588.manager.bundle.js 3.77 MiB main.manager.bundle.js 818 bytes
orphan modules 1.51 MiB [orphan] 350 modules
runtime modules 8.34 KiB 13 modules
javascript modules 4.01 MiB 797 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]   
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]manager (webpack 5.54.0) compiled successfully in 4172 ms
webpack built preview c251a0c7c61cf3fc8dc9 in 4868ms
ERROR in ./node_modules/sku/config/storybook/start/generated-stories-entry.js 7:37-146
Module not found: Error: Can't resolve 'C:UsersMauriciosites
d-braidsrc' in 'C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start' 

preview compiled with 1 error
ModuleNotFoundError: Module not found: Error: Can't resolve 'C:UsersMauriciosites
d-braidsrc' in 'C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start' 
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\lib\Compilation.js:1779:28   
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\lib\ContextModuleFactory.js:210:15
    at C:\Users\Mauricio\sites\nd-braid\node_modules\neo-async\async.js:2830:7
    at C:\Users\Mauricio\sites\nd-braid\node_modules\neo-async\async.js:6877:13
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\lib\ContextModuleFactory.js:180:26
    at finishWithoutResolve (C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\forEachBail.js:16:12
    at C:\Users\Mauricio\sites\nd-braid\node_modules\webpack\node_modules\enhanced-resolve\lib\AliasPlugin.js:103:14
resolve 'C:UsersMauriciosites
d-braidsrc' in 'C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start' 
  Parsed request is a module
  using description file: C:\Users\Mauricio\sites\nd-braid\node_modules\sku\package.json (relative path: ./config/storybook/start)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\start\node_modules doesn't exist or is not a directory
      C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\storybook\node_modules doesn't exist or is not a directory
      C:\Users\Mauricio\sites\nd-braid\node_modules\sku\config\node_modules doesn't exist 
or is not a directory
      looking for modules in C:\Users\Mauricio\sites\nd-braid\node_modules\sku\node_modules
        C:\Users\Mauricio\sites\nd-braid\node_modules\sku\node_modules\C:UsersMauriciosites
d-braidsrc doesn't exist
      C:\Users\Mauricio\sites\nd-braid\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Mauricio\sites\nd-braid\node_modules
        C:\Users\Mauricio\sites\nd-braid\node_modules\C:UsersMauriciosites
d-braidsrc doesn't exist
      looking for modules in C:\Users\Mauricio\sites\node_modules
        C:\Users\Mauricio\sites\node_modules\C:UsersMauriciosites
d-braidsrc doesn't exist
      looking for modules in C:\Users\Mauricio\node_modules
        C:\Users\Mauricio\node_modules\C:UsersMauriciosites
d-braidsrc doesn't exist
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

`

This part of the error shows a wrong path:

 Module not found: Error: Can't resolve 'C:UsersMauriciositesnd-braidsrc

The path should be: C:Users\Mauricio\sites\nd-braid\src

How can this issue be fixed on a Windows machine?

Kind regards

**Comment by askoufis** [comment] 2023-06-27 02:02
Closing this issue due to a lack of reproduction. It might've been fixed in a newer versino of sku now that we're using storybook v7. Please create a new issue if you're still encountering this error.

**Closed by askoufis** 2023-06-27 02:02 UTC
